Fix running scripts

diff --git a/chezmoi/.chezmoiscripts/run_after_00-run-scripts-by-os.sh.tmpl b/chezmoi/.chezmoiscripts/run_after_00-run-scripts-by-os.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_after_00-run-scripts-by-os.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_after_00-run-scripts-by-os.sh.tmpl
@@ -14,5 +14,6 @@ SCRIPTS_DIR={{ .chezmoi.workingTree }}/scripts
 for script in $SCRIPTS_DIR/$OS/*.*sh
 do
   echo $script
-  source $script
+  # Run script file, ignoring exit code so that we can run all scripts in the directory
+  bash $script || true
 done
